apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
commonAnnotations:
  supported-by: sre@example.com
namespace: staging
labels:
- includeSelectors: false
  pairs:
    project: instavote
patches:
- path: service.yaml
